### PR TITLE
use lodash.assign instead of deprecated lodash-node

### PR DESCRIPTION
**Pull request by akatov**

### CODE REVIEW

**Comment by jdalton** [comment]
Or `require('lodash/object/assign')` from the primary package.

**Comment by akatov** [comment]
@twokul would you mind releasing a new version of leek? I'm trying to get rid of all the lodash deprecation warnings in ember-cli...

**Comment by twokul** [comment]
@akatov published as `0.0.20`

**Comment by jdalton** [comment]
:clap:

**Comment by akatov** [comment]
:+1:

**Pull request merged**
